//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiNhanhDiaChi
    {
        public int Idchinhanh { get; set; }
        public string Thanhpho { get; set; }
        public string Quan { get; set; }
        public string Phuong { get; set; }
        public string Duong { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
    }
}
