//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiNhanhMonAn
    {
        public int Idchinhanh { get; set; }
        public int Idmonan { get; set; }
        public Nullable<int> Soluongcon { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
