//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.MonAnDonHangs = new HashSet<MonAnDonHang>();
            this.PhieuGiaoHangs = new HashSet<PhieuGiaoHang>();
        }
    
        public int Iddondathang { get; set; }
        public string Magiamgia { get; set; }
        public Nullable<int> Idchinhanh { get; set; }
        public string Tennguoidat { get; set; }
        public string Sodt { get; set; }
        public string Tinhtrang { get; set; }
        public Nullable<System.DateTime> Ngaydathang { get; set; }
        public string Kenhdathang { get; set; }
        public Nullable<int> Idkhachhang { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual MaGiamGia MaGiamGia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonAnDonHang> MonAnDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuGiaoHang> PhieuGiaoHangs { get; set; }
    }
}
