//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.HoaDonChiTiets = new HashSet<HoaDonChiTiet>();
        }
    
        public int Idhoadon { get; set; }
        public Nullable<int> Iddondathang { get; set; }
        public Nullable<double> Tiengiam { get; set; }
        public Nullable<double> Tongtien { get; set; }
        public Nullable<double> Thanhtien { get; set; }
        public Nullable<System.DateTime> Ngaylap { get; set; }
        public Nullable<System.TimeSpan> Giovao { get; set; }
        public Nullable<int> Ca { get; set; }
        public Nullable<int> Ban { get; set; }
        public Nullable<int> Nhanvienghidon { get; set; }
    
        public virtual Ban Ban1 { get; set; }
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonChiTiet> HoaDonChiTiets { get; set; }
    }
}
