//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuGiaoHang
    {
        public int Idphieugiaohang { get; set; }
        public Nullable<int> Iddondathang { get; set; }
        public Nullable<System.DateTime> Ngaygiaodukien { get; set; }
        public Nullable<System.DateTime> Ngaygiaothucte { get; set; }
        public Nullable<double> Phigiaohang { get; set; }
        public Nullable<int> Nhanviengiaohang { get; set; }
        public string Phuong { get; set; }
        public string Tinh { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
